"""Historial de uploads de tarifas y su reversa.

Cada archivo que se inserta es un LOTE (`batch_id`, incluye sus versiones por commodity): se guarda
qué tarifas creó (columna `tariff_ids`, JSON) y quién/cuándo (`airtariff_uploads`). Revertir un lote
quita lo que insertó:

- Las tarifas (y sus `tariff_feeds`) que nadie usa se BORRAN.
- Las que ya se usaron (cotizaciones, cálculos, historial de búsquedas) o son base de otra tarifa se
  DESACTIVAN (`active = 0`): borrarlas dejaría esas cotizaciones apuntando a una tarifa que no existe.
- Las reglas de fees (`air_fee_rules`) que creó el upload (fees especiales de sus versiones) se borran.

La tabla (`airtariff_uploads`, una sola) la crea este mismo servicio la primera vez que la usa
(`ensure_table`, CREATE TABLE IF NOT EXISTS): no hay SQL que ejecutar a mano. Si el usuario de la BD no
tiene permiso para crearla, el upload sigue funcionando y solo falta el registro (`tracked: false`).
"""
import json
import os
import re
import uuid
from datetime import datetime

import mysql.connector

import tariff_archive
from db_conn import db_conn

PROFILE = os.getenv("MYSQL_PROFILE", "local")
TYPE_TARIFF_AIR = 3
CHUNK = 500

# Tablas/columnas que apuntan a un tariffs.id: si una tarifa aparece ahí no se borra, se desactiva.
REFERENCES = (
    ("quotes", "tariff_id"),
    ("calculations", "tariff_id"),
    ("history_instant_air_result_feeds", "tariff_id"),
    ("tariffs", "clone_tariff_id"),
    ("tariffs", "autogenerated_tariff_id"),
    ("tariffs", "one_tariff_id"),
    ("tariffs", "two_tariff_id"),
)

MISSING_TABLE, MISSING_COLUMN = 1146, 1054

SCHEMA = """
CREATE TABLE IF NOT EXISTS airtariff_uploads (
    id                  INT UNSIGNED NOT NULL AUTO_INCREMENT,
    batch_id            VARCHAR(36)  NOT NULL,
    file_name           VARCHAR(255) NULL,
    airline_id          INT NULL,
    provider_id         INT NULL,
    commodity_id        INT NULL,
    valid_to            DATE NULL,
    tariffs             INT UNSIGNED NOT NULL DEFAULT 0,
    fees                INT UNSIGNED NOT NULL DEFAULT 0,
    tariff_ids          MEDIUMTEXT NOT NULL,
    rule_ids            TEXT NULL,
    run_id              VARCHAR(36) NULL,
    uploaded_by         VARCHAR(120) NULL,
    status              VARCHAR(12)  NOT NULL DEFAULT 'active',
    reverted_at         TIMESTAMP NULL,
    reverted_by         VARCHAR(120) NULL,
    deleted_tariffs     INT UNSIGNED NULL,
    deactivated_tariffs INT UNSIGNED NULL,
    deleted_rules       INT UNSIGNED NULL,
    edited_at           TIMESTAMP NULL,
    edited_by           VARCHAR(120) NULL,
    edit_log            MEDIUMTEXT NULL,
    created_at          TIMESTAMP NULL,
    PRIMARY KEY (id),
    KEY airtariff_uploads_batch_id_index (batch_id),
    KEY airtariff_uploads_created_at_index (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
"""

# Columnas agregadas despues de la primera version de la tabla: si la tabla ya existia sin ellas se
# agregan (MySQL no tiene ADD COLUMN IF NOT EXISTS).
EXTRA_COLUMNS = {
    "run_id": "VARCHAR(36) NULL",
    "edited_at": "TIMESTAMP NULL",
    "edited_by": "VARCHAR(120) NULL",
    "edit_log": "MEDIUMTEXT NULL",
}

_table_ready: bool | None = None  # None = aun no se intento en este proceso


def ensure_table() -> bool:
    """Crea la tabla si falta y agrega las columnas nuevas si ya existia (una vez por proceso).

    False si no hay permiso para crearla. Se llama ANTES de abrir la transaccion del insert: un
    CREATE/ALTER TABLE hace commit implicito. Se consulta information_schema en vez de usar
    CREATE TABLE IF NOT EXISTS porque la conexion convierte sus avisos en errores.
    """
    global _table_ready
    if _table_ready is not None:
        return _table_ready
    try:
        with db_conn(PROFILE, pooled=False) as conn, conn.cursor() as cur:
            cur.execute(
                "SELECT column_name FROM information_schema.columns "
                "WHERE table_schema = DATABASE() AND table_name = 'airtariff_uploads'"
            )
            have = {r[0] for r in cur.fetchall()}
            if not have:
                cur.execute(SCHEMA)
            else:
                for col, ddl in EXTRA_COLUMNS.items():
                    if col not in have:
                        cur.execute(f"ALTER TABLE airtariff_uploads ADD COLUMN {col} {ddl}")
            conn.commit()
        _table_ready = True
    except mysql.connector.errors.Error:
        # Sin permiso de CREATE/ALTER (u otro error de la BD): se reintenta en el proximo proceso.
        _table_ready = False
    return _table_ready


class TrackingUnavailable(RuntimeError):
    """La tabla del historial no existe y no se pudo crear."""


class BatchNotFound(LookupError):
    pass


class AlreadyReverted(ValueError):
    pass


def _chunks(items: list, size: int = CHUNK):
    for i in range(0, len(items), size):
        yield items[i : i + size]


def _marks(n: int) -> str:
    return ",".join(["%s"] * n)


def record_upload(cur, header: dict, tariff_ids: list[int], fee_count: int) -> str | None:
    """Registra el lote DENTRO de la transaccion del insert. None si la tabla no existe."""
    batch_id = (header.get("batch_id") or "").strip() or str(uuid.uuid4())
    try:
        cur.execute(
            "INSERT INTO airtariff_uploads (batch_id, file_name, airline_id, provider_id, commodity_id, "
            "valid_to, tariffs, fees, tariff_ids, run_id, uploaded_by, status, created_at) "
            "VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,'active',NOW())",
            (
                batch_id[:36],
                (header.get("source_file") or None) and str(header["source_file"])[:255],
                header.get("airline_id"),
                header.get("provider_id"),
                header.get("commodity_id"),
                header.get("valid_to"),
                len(tariff_ids),
                fee_count,
                json.dumps(tariff_ids),
                (header.get("run_id") or None) and str(header["run_id"])[:36],
                (header.get("uploaded_by") or None) and str(header["uploaded_by"])[:120],
            ),
        )
    except mysql.connector.errors.ProgrammingError as e:
        # 1146 = la tabla no existe, 1054 = le faltan columnas: el upload entra igual, sin registro.
        if e.errno in (MISSING_TABLE, MISSING_COLUMN):
            return None
        raise
    return batch_id[:36]


def _fmt(dt) -> str | None:
    return dt.strftime("%Y-%m-%d %H:%M") if dt else None


def list_uploads(limit: int = 30) -> dict:
    """Últimos lotes (más nuevos primero). `tracking` = False si las tablas no existen aún."""
    sql = (
        "SELECT u.id, u.batch_id, u.file_name, u.airline_id, a.fullname, p.fullname, u.commodity_id, c.fullname, "
        "u.valid_to, u.tariffs, u.fees, u.rule_ids, u.uploaded_by, u.status, u.created_at, u.reverted_at, "
        "u.reverted_by, u.deleted_tariffs, u.deactivated_tariffs, u.deleted_rules, "
        "u.run_id, u.provider_id, u.edited_at, u.edited_by, u.edit_log "
        "FROM airtariff_uploads u "
        "LEFT JOIN companies a ON a.id = u.airline_id "
        "LEFT JOIN companies p ON p.id = u.provider_id "
        "LEFT JOIN commodities c ON c.id = u.commodity_id "
        "ORDER BY u.created_at DESC, u.id DESC LIMIT 800"
    )
    ensure_table()
    with db_conn(PROFILE, pooled=False) as conn, conn.cursor() as cur:
        try:
            cur.execute(sql)
        except mysql.connector.errors.ProgrammingError as e:
            if e.errno == MISSING_TABLE:
                return {"tracking": False, "uploads": []}
            raise
        rows = cur.fetchall()

    batches: dict[str, dict] = {}
    for (uid, batch, fname, air_id, air, prov, com_id, com, valid_to, tariffs, fees, rule_ids, by, status,
         created, rev_at, rev_by, del_t, deact_t, del_r, run_id, prov_id, ed_at, ed_by, ed_log) in rows:
        b = batches.get(batch)
        if b is None:
            if len(batches) >= limit:
                continue
            b = batches[batch] = {
                "batch_id": batch, "file_name": fname, "airline_id": air_id, "airline": air,
                "provider": prov, "valid_to": valid_to.strftime("%Y-%m-%d") if valid_to else None,
                "provider_id": prov_id, "run_id": run_id, "edited_at": None, "edited_by": None, "edits": 0,
                "uploaded_by": by, "created_at": _fmt(created), "parts": [], "tariffs": 0, "fees": 0,
                "rules": 0, "reverted_at": None, "reverted_by": None, "deleted_tariffs": 0,
                "deactivated_tariffs": 0, "deleted_rules": 0,
            }
        b["parts"].append({"upload_id": uid, "commodity_id": com_id, "commodity": com, "tariffs": tariffs,
                           "fees": fees, "status": status})
        b["tariffs"] += tariffs
        b["fees"] += fees
        if ed_at and not b["edited_at"]:
            b["edited_at"], b["edited_by"] = _fmt(ed_at), ed_by
            b["edits"] = len(json.loads(ed_log)) if ed_log else 1
        b["rules"] += len(json.loads(rule_ids)) if rule_ids else 0
        if status == "reverted":
            b["reverted_at"], b["reverted_by"] = _fmt(rev_at), rev_by
            b["deleted_tariffs"] += del_t or 0
            b["deactivated_tariffs"] += deact_t or 0
            b["deleted_rules"] += del_r or 0
        if not b["file_name"]:
            b["file_name"] = fname
    out = []
    for b in batches.values():
        b["status"] = "reverted" if all(p["status"] == "reverted" for p in b["parts"]) else "active"
        b["parts"].reverse()  # cronológico: primero el commodity base
        out.append(b)
    return {"tracking": True, "uploads": out}


def attach_rules(batch_id: str, rule_ids: list[int]) -> int:
    """Asocia reglas de fees (air_fee_rules) creadas por el upload, para borrarlas si se revierte."""
    ids = sorted({int(i) for i in rule_ids})
    if not ids:
        return 0
    ensure_table()
    with db_conn(PROFILE, pooled=False) as conn, conn.cursor() as cur:
        try:
            cur.execute("SELECT id, rule_ids FROM airtariff_uploads WHERE batch_id = %s ORDER BY id DESC LIMIT 1", (batch_id,))
        except mysql.connector.errors.ProgrammingError as e:
            if e.errno == MISSING_TABLE:
                raise TrackingUnavailable("The upload history table does not exist and could not be created.") from e
            raise
        row = cur.fetchone()
        if not row:
            raise BatchNotFound(batch_id)
        merged = sorted(set(json.loads(row[1]) if row[1] else []) | set(ids))
        cur.execute("UPDATE airtariff_uploads SET rule_ids = %s WHERE id = %s", (json.dumps(merged), row[0]))
        conn.commit()
    return len(merged)


def _used_tariff_ids(cur, ids: list[int]) -> set[int]:
    used: set[int] = set()
    for table, col in REFERENCES:
        for chunk in _chunks(ids):
            try:
                cur.execute(f"SELECT DISTINCT {col} FROM {table} WHERE {col} IN ({_marks(len(chunk))})", chunk)
            except mysql.connector.errors.ProgrammingError as e:
                if e.errno in (MISSING_TABLE, MISSING_COLUMN):
                    break  # esa tabla/columna no existe en esta BD
                raise
            used.update(r[0] for r in cur.fetchall() if r[0] is not None)
    return used


def _count_replaced(cur, batch_id: str) -> int:
    try:
        cur.execute(
            "SELECT COUNT(*) FROM airtariff_archive WHERE replaced_by_batch = %s AND restored_at IS NULL", (batch_id,)
        )
        return int(cur.fetchone()[0])
    except mysql.connector.errors.ProgrammingError as e:
        if e.errno == MISSING_TABLE:
            return 0
        raise


def revert_batch(batch_id: str, reverted_by: str | None = None, dry_run: bool = False) -> dict:
    """Revierte un lote. Con dry_run solo cuenta lo que pasaría, sin tocar nada."""
    ensure_table()
    with db_conn(PROFILE, pooled=False) as conn, conn.cursor() as cur:
        try:
            cur.execute("SELECT id, status, rule_ids, tariff_ids FROM airtariff_uploads WHERE batch_id = %s", (batch_id,))
        except mysql.connector.errors.ProgrammingError as e:
            if e.errno == MISSING_TABLE:
                raise TrackingUnavailable("The upload history table does not exist and could not be created.") from e
            raise
        parts = cur.fetchall()
        if not parts:
            raise BatchNotFound(batch_id)
        active = [p for p in parts if p[1] == "active"]
        if not active:
            raise AlreadyReverted(batch_id)
        upload_ids = [p[0] for p in active]

        ids = sorted({int(t) for p in active for t in (json.loads(p[3]) if p[3] else [])})
        existing: set[int] = set()
        for chunk in _chunks(ids):
            cur.execute(
                f"SELECT id FROM tariffs WHERE type_tariff = %s AND id IN ({_marks(len(chunk))})",
                [TYPE_TARIFF_AIR, *chunk],
            )
            existing.update(r[0] for r in cur.fetchall())
        used = _used_tariff_ids(cur, sorted(existing))
        to_delete = sorted(existing - used)
        to_deactivate = sorted(existing & used)

        fees = 0
        for chunk in _chunks(to_delete):
            cur.execute(f"SELECT COUNT(*) FROM tariff_feeds WHERE tariff_id IN ({_marks(len(chunk))})", chunk)
            fees += cur.fetchone()[0]

        rule_ids = sorted({int(i) for p in active for i in (json.loads(p[2]) if p[2] else [])})
        rules_existing: list[int] = []
        if rule_ids:
            try:
                cur.execute(f"SELECT id FROM air_fee_rules WHERE id IN ({_marks(len(rule_ids))})", rule_ids)
                rules_existing = [r[0] for r in cur.fetchall()]
            except mysql.connector.errors.ProgrammingError as e:
                if e.errno != MISSING_TABLE:
                    raise

        result = {
            "batch_id": batch_id,
            "dry_run": dry_run,
            "tariffs_in_upload": len(ids),
            "deleted_tariffs": len(to_delete),
            "deleted_fees": fees,
            "deactivated_tariffs": len(to_deactivate),
            "already_gone": len(ids) - len(existing),
            "deleted_rules": len(rules_existing),
            # Para que el office las quite de su lista de reglas.
            "rule_ids": rules_existing,
            # Tarifas que este lote mandó al histórico (al reemplazarlas): vuelven a estar vigentes.
            "restored_from_history": _count_replaced(cur, batch_id),
        }
        if dry_run:
            return result

        try:
            for chunk in _chunks(to_delete):
                cur.execute(f"DELETE FROM tariff_feeds WHERE tariff_id IN ({_marks(len(chunk))})", chunk)
                cur.execute(f"DELETE FROM tariffs WHERE type_tariff = %s AND id IN ({_marks(len(chunk))})",
                            [TYPE_TARIFF_AIR, *chunk])
            for chunk in _chunks(to_deactivate):
                cur.execute(f"UPDATE tariffs SET active = 0, updated_at = NOW() WHERE id IN ({_marks(len(chunk))})", chunk)
            if rules_existing:
                cur.execute(f"DELETE FROM air_fee_rules WHERE id IN ({_marks(len(rules_existing))})", rules_existing)
            result["restored_from_history"] = tariff_archive.restore_by_replacer(cur, batch_id, reverted_by)
            cur.execute(
                f"UPDATE airtariff_uploads SET status = 'reverted', reverted_at = NOW(), reverted_by = %s, "
                f"deleted_tariffs = 0, deactivated_tariffs = 0, deleted_rules = 0 "
                f"WHERE id IN ({_marks(len(upload_ids))})",
                [(reverted_by or None), *upload_ids],
            )
            # Los totales van en un solo renglón del lote (el listado los suma).
            cur.execute(
                "UPDATE airtariff_uploads SET deleted_tariffs = %s, deactivated_tariffs = %s, deleted_rules = %s "
                "WHERE id = %s",
                (len(to_delete), len(to_deactivate), len(rules_existing), upload_ids[0]),
            )
            conn.commit()
        except Exception:
            conn.rollback()
            raise
        return result


EDITABLE = ("airline_id", "provider_id", "commodity_id", "valid_to", "airchaft")


class EditNotAllowed(ValueError):
    """La edicion pedida no se puede aplicar (upload revertido, varios commodities, valores invalidos)."""


RATE_COLUMNS = ("n", "forty_five_more", "hundred_more", "three_hundred_more", "five_hundred_more", "thousand_more")
ADJUST_TARGETS = ("rates", "min", *RATE_COLUMNS)


def adjust_columns(target: str) -> tuple[str, ...]:
    return RATE_COLUMNS if target == "rates" else (target,)


def adjust_apply(old, column: str, op: str, value: float):
    """Valor nuevo de una celda: null se queda null, nunca baja de 0; 2 decimales (el minimo, entero)."""
    if old is None:
        return None
    new = old * (1 + value / 100) if op == "pct" else old + value
    new = max(0.0, new)
    return int(round(new)) if column == "min" else round(new, 2)


def adjust_sets(adjust: list[dict]) -> tuple[list[str], list]:
    """`columna = expresion` y sus parametros: el mismo calculo que AirTariffAdjust.php del backend."""
    expr: dict[str, str] = {}
    params: dict[str, list] = {}
    for a in adjust:
        for col in adjust_columns(a["target"]):
            cur = expr.get(col, f"`{col}`")
            calc = f"({cur}) * (1 + %s / 100)" if a["op"] == "pct" else f"({cur}) + %s"
            expr[col] = f"ROUND(GREATEST(0, {calc}), {0 if col == 'min' else 2})"
            params[col] = [*params.get(col, []), a["value"]]
    return [f"`{c}` = {e}" for c, e in expr.items()], [v for c in expr for v in params[c]]


def adjust_text(a: dict) -> str:
    v = a["value"]
    num = f"{abs(v):g}"
    amount = f"{'+' if v >= 0 else '−'}{num} %" if a["op"] == "pct" else f"{'+' if v >= 0 else '−'}{num} USD"
    what = {"rates": "all per-kg rates", "min": "the minimum charge"}.get(a["target"], f"the {a['target']} break")
    return f"{amount} on {what}"


def _clean_adjust(raw) -> list[dict]:
    if not raw:
        return []
    if not isinstance(raw, list) or len(raw) > 10:
        raise EditNotAllowed("adjust must be a list of up to 10 adjustments.")
    out = []
    for a in raw:
        try:
            target, op, value = a["target"], a["op"], float(a["value"])
        except (KeyError, TypeError, ValueError):
            raise EditNotAllowed("Each adjustment needs a target, an operation and a number.") from None
        if target not in ADJUST_TARGETS or op not in ("pct", "add"):
            raise EditNotAllowed("Invalid adjustment.")
        if op == "pct" and value <= -100:
            raise EditNotAllowed("A percentage cut must be smaller than 100 %.")
        out.append({"target": target, "op": op, "value": value})
    return out


def _clean_changes(changes: dict) -> dict:
    out: dict = {}
    adjust = _clean_adjust(changes.get("adjust"))
    if adjust:
        out["adjust"] = adjust
    for k in EDITABLE:
        v = changes.get(k)
        if v in (None, ""):
            continue
        if k == "valid_to":
            if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", str(v)):
                raise EditNotAllowed("valid_to must be a date (YYYY-MM-DD).")
            out[k] = str(v)
        else:
            try:
                out[k] = int(v)
            except (TypeError, ValueError):
                raise EditNotAllowed(f"{k} must be a number.") from None
    if "airchaft" in out and out["airchaft"] not in (1, 2, 3):
        raise EditNotAllowed("airchaft must be 1 (CAO), 2 (PAX) or 3 (CAO/PAX).")
    if not out:
        raise EditNotAllowed("Nothing to change.")
    return out


def _adjust_samples(cur, ids: list[int], adjust: list[dict]) -> list[dict]:
    """Hasta 3 tarifas de la seleccion con sus valores antes -> despues, para revisar el ajuste."""
    cols = sorted({c for a in adjust for c in adjust_columns(a["target"])})
    pick = sorted(ids)[:3]
    if not pick:
        return []
    cur.execute(
        f"SELECT t.id, o.codigo, d.codigo, a.fullname, {', '.join('t.`' + c + '`' for c in cols)} FROM tariffs t "
        "LEFT JOIN transports o ON o.id = t.origin_id LEFT JOIN transports d ON d.id = t.destin_id "
        f"LEFT JOIN companies a ON a.id = t.airline_id WHERE t.id IN ({_marks(len(pick))}) ORDER BY t.id",
        pick,
    )
    out = []
    for row in cur.fetchall():
        before = {c: (float(v) if v is not None else None) for c, v in zip(cols, row[4:])}
        after = dict(before)
        for a in adjust:
            for c in adjust_columns(a["target"]):
                after[c] = adjust_apply(after[c], c, a["op"], a["value"])
        label = f"{row[3] or ''} · {(row[1] or '').strip()} → {(row[2] or '').strip()}".strip(" ·")
        out.append({"id": row[0], "label": label, "before": before, "after": after})
    return out


def edit_batches(batch_ids: list[str], changes: dict, edited_by: str | None = None, dry_run: bool = False) -> dict:
    """Cambia aerolinea / proveedor / commodity / vigencia / tipo de avion de TODAS las tarifas de esos uploads.

    Para corregir un error de captura de toda una tanda de PDFs. Tambien se actualizan las reglas de fees
    (`air_fee_rules`) que creo el upload y su historial. Con dry_run solo cuenta lo que pasaria. El
    commodity solo se puede cambiar si cada upload tiene un unico commodity (sin versiones).
    """
    changes = _clean_changes(changes)
    ids_in = sorted({b for b in batch_ids if b})
    if not ids_in:
        raise EditNotAllowed("Pick at least one upload.")
    ensure_table()
    with db_conn(PROFILE, pooled=False) as conn, conn.cursor() as cur:
        try:
            cur.execute(
                "SELECT id, batch_id, status, file_name, airline_id, provider_id, commodity_id, valid_to, tariff_ids, "
                f"rule_ids, edit_log FROM airtariff_uploads WHERE batch_id IN ({_marks(len(ids_in))})",
                ids_in,
            )
        except mysql.connector.errors.ProgrammingError as e:
            if e.errno == MISSING_TABLE:
                raise TrackingUnavailable("The upload history table does not exist and could not be created.") from e
            raise
        rows = cur.fetchall()
        found = {r[1] for r in rows}
        if set(ids_in) - found:
            raise BatchNotFound(", ".join(sorted(set(ids_in) - found)))

        parts: dict[str, list] = {}
        for r in rows:
            parts.setdefault(r[1], []).append(r)
        active_parts: list = []
        for b in ids_in:
            act = [p for p in parts[b] if p[2] == "active"]
            if not act:
                raise EditNotAllowed(f"\"{parts[b][0][3] or b}\" was reverted: it cannot be edited.")
            if "commodity_id" in changes and len(act) > 1:
                raise EditNotAllowed(
                    f"\"{act[0][3] or b}\" was loaded with several commodities (versions): change its commodity "
                    "from each card, or leave the commodity as it is."
                )
            active_parts.extend(act)

        tariff_ids = sorted({int(t) for p in active_parts for t in (json.loads(p[8]) if p[8] else [])})
        existing: list[int] = []
        for chunk in _chunks(tariff_ids):
            cur.execute(f"SELECT id FROM tariffs WHERE type_tariff = %s AND id IN ({_marks(len(chunk))})",
                        [TYPE_TARIFF_AIR, *chunk])
            existing.extend(r[0] for r in cur.fetchall())
        selected = set(existing)

        # Tarifas que, con el cambio, coincidirian con otra vigente que NO es de la seleccion.
        dup = 0
        if {"airline_id", "provider_id", "commodity_id"} & set(changes):
            clashing: set[int] = set()
            for chunk in _chunks(existing):
                cur.execute(
                    "SELECT t.id, o.id FROM tariffs t JOIN tariffs o ON o.origin_id = t.origin_id AND o.destin_id = t.destin_id "
                    "AND o.airline_id = COALESCE(%s, t.airline_id) AND o.provider_id = COALESCE(%s, t.provider_id) "
                    "AND o.comodity_id = COALESCE(%s, t.comodity_id) AND o.type_tariff = %s AND o.active = 1 "
                    "AND DATEDIFF(o.f_end, NOW()) >= 1 AND o.id <> t.id "
                    f"WHERE t.id IN ({_marks(len(chunk))})",
                    [changes.get("airline_id"), changes.get("provider_id"), changes.get("commodity_id"), TYPE_TARIFF_AIR, *chunk],
                )
                clashing.update(t for t, o in cur.fetchall() if o not in selected)
            dup = len(clashing)

        rule_ids = sorted({int(i) for p in active_parts for i in (json.loads(p[9]) if p[9] else [])})
        rules: list[tuple[int, str]] = []
        if rule_ids:
            try:
                cur.execute(f"SELECT id, conditions FROM air_fee_rules WHERE id IN ({_marks(len(rule_ids))})", rule_ids)
                rules = [(r[0], r[1]) for r in cur.fetchall()]
            except mysql.connector.errors.ProgrammingError as e:
                if e.errno != MISSING_TABLE:
                    raise

        # De -> a, usando el valor registrado de cada upload (puede haber varios distintos), con NOMBRES
        # (aerolinea, proveedor, commodity) para que el resumen se entienda.
        col = {"airline_id": 4, "provider_id": 5, "commodity_id": 6, "valid_to": 7}
        table = {"airline_id": "companies", "provider_id": "companies", "commodity_id": "commodities"}
        aircraft = {1: "CAO", 2: "PAX", 3: "CAO/PAX"}

        def names(field: str, values: set) -> dict:
            vals = sorted(v for v in values if v is not None)
            if field not in table or not vals:
                return {}
            cur.execute(f"SELECT id, fullname FROM {table[field]} WHERE id IN ({_marks(len(vals))})", vals)
            return {i: n for i, n in cur.fetchall()}

        summary: dict = {}
        for field in changes:
            if field == "adjust":
                summary[field] = {"from": None, "to": "; ".join(adjust_text(a) for a in changes[field])}
            elif field in table:
                nm = names(field, {p[col[field]] for p in active_parts} | {changes[field]})
                olds = sorted({nm.get(p[col[field]], str(p[col[field]])) for p in active_parts if p[col[field]] is not None})
                summary[field] = {"from": olds, "to": nm.get(changes[field], str(changes[field]))}
            elif field == "valid_to":
                olds = sorted({p[7].strftime("%Y-%m-%d") for p in active_parts if p[7]})
                summary[field] = {"from": olds, "to": changes[field]}
            else:
                summary[field] = {"from": None, "to": aircraft.get(changes[field], str(changes[field]))}
        result = {
            "dry_run": dry_run,
            "uploads": len(ids_in),
            "tariffs": len(existing),
            "rules": len(rules),
            "duplicates": dup,
            "changes": summary,
        }
        if "adjust" in changes:
            result["samples"] = _adjust_samples(cur, existing[:200], changes["adjust"])
        if dry_run:
            return result

        sets, params = [], []
        for field, tcol in (("airline_id", "airline_id"), ("provider_id", "provider_id"), ("commodity_id", "comodity_id"),
                            ("valid_to", "f_end"), ("airchaft", "airchaft")):
            if field in changes:
                sets.append(f"{tcol} = %s")
                params.append(changes[field])
        if "adjust" in changes:
            adj_sets, adj_params = adjust_sets(changes["adjust"])
            sets += adj_sets
            params += adj_params
        try:
            for chunk in _chunks(existing):
                cur.execute(
                    f"UPDATE tariffs SET {', '.join(sets)}, updated_at = NOW() "
                    f"WHERE type_tariff = %s AND id IN ({_marks(len(chunk))})",
                    [*params, TYPE_TARIFF_AIR, *chunk],
                )
            # Reglas de fees del upload: siguen a la aerolinea; y a su proveedor / commodity en `conditions`.
            old_prov = {p[5] for p in active_parts if p[5] is not None}
            old_com = {p[6] for p in active_parts if p[6] is not None}
            for rid, cond in rules:
                c = json.loads(cond) if cond else {}
                if "provider_id" in changes and c.get("provider_in"):
                    c["provider_in"] = sorted({changes["provider_id"] if x in old_prov else x for x in c["provider_in"]})
                if "commodity_id" in changes and c.get("commodity_in"):
                    c["commodity_in"] = sorted({changes["commodity_id"] if x in old_com else x for x in c["commodity_in"]})
                cur.execute(
                    "UPDATE air_fee_rules SET conditions = %s" + (", airline_id = %s" if "airline_id" in changes else "") +
                    ", updated_at = NOW() WHERE id = %s",
                    [json.dumps(c), *([changes["airline_id"]] if "airline_id" in changes else []), rid],
                )
            entry = {"at": datetime.now().strftime("%Y-%m-%d %H:%M"), "by": edited_by, "changes": summary}
            for p in active_parts:
                log = json.loads(p[10]) if p[10] else []
                log.append(entry)
                ups, uparams = [], []
                for field, ucol in (("airline_id", "airline_id"), ("provider_id", "provider_id"),
                                    ("commodity_id", "commodity_id"), ("valid_to", "valid_to")):
                    if field in changes:
                        ups.append(f"{ucol} = %s")
                        uparams.append(changes[field])
                cur.execute(
                    f"UPDATE airtariff_uploads SET {', '.join(ups + ['edited_at = NOW()', 'edited_by = %s', 'edit_log = %s'])} WHERE id = %s",
                    [*uparams, edited_by, json.dumps(log), p[0]],
                )
            conn.commit()
        except Exception:
            conn.rollback()
            raise
        return result
